// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int under = 0;
		int over = 0;
		double  d = 0;
	    for (int  i = 0; i < Integer.parseInt(args[0]); i++) {
			d = Math.random();
			if (d > 0.5) {
                over++;
            } else {
                under++;
            }
		}
		System.out.println("> 0.5: " + over + " times");
		System.out.println("<= 0.5: " + under + " times");
		if (over > 0 && under > 0) {
			double ratio = (double) over / (double) under;
			System.out.println("Ratio: " + ratio);
		}
	}
}
